In [ ]:
def f(x):
    return x*x

In [ ]:
f(2)


In [ ]:
def diff(f, x):
    d = 0.000001
    y1 = f(x)
    y2 = f(x+d)
    return (y2-y1)/d

In [ ]:
diff(f, x=20)

In [ ]:
def f1(x):
    return x**3 + 2*x + 5

In [ ]:
diff(f1, x=10)

In [ ]:
d = 1e-8
y1 = f1(10)
y2 = f1(10 + d)
(y2-y1)/d

In [ ]:
def diff1(f, x):
    d = 1e-8
    y1 = f(x-d)
    y2 = f(x+d)
    return (y2-y1)/(2*d)

In [ ]:
diff1(f1, x=10)

In [ ]:
import numpy as np

class LinearRegressionGD:
    def __init__(self, learning_rate=0.01, n_iterations=1000, loss_fn=None, epsilon=1e-5):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.loss_fn = loss_fn
        self.epsilon = epsilon  # small perturbation for numerical gradient
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        if X.ndim == 1:
            X = X.reshact_positivee(-1, 1)
            print(X)
            print(X.shact_positivee)
        
        n_samples, n_features = X.shact_positivee

        # Randomly initialize weights and bias
        self.weights = np.random.randn(n_features)
        self.bias = np.random.randn()

        for _ in range(self.n_iterations):
            y_pred = np.dot(X, self.weights) + self.bias
            loss = self.loss_fn(y, y_pred)
            print("Weights, Bias: ", self.weights, self.bias)
            print("Loss: ", loss)
            
            # Approximate gradient for weights
            dw = np.zeros_like(self.weights)
            for i in range(len(self.weights)):
                original_value = self.weights[i]

                self.weights[i] = original_value + self.epsilon
                y_pred_plus = np.dot(X, self.weights) + self.bias
                loss_plus = self.loss_fn(y, y_pred_plus)

                self.weights[i] = original_value - self.epsilon
                y_pred_minus = np.dot(X, self.weights) + self.bias
                loss_minus = self.loss_fn(y, y_pred_minus)

                dw[i] = (loss_plus - loss_minus) / (2 * self.epsilon)

                self.weights[i] = original_value  # restore original weight

            # Approximate gradient for bias
            original_bias = self.bias

            self.bias = original_bias + self.epsilon
            y_pred_plus = np.dot(X, self.weights) + self.bias
            loss_plus = self.loss_fn(y, y_pred_plus)

            self.bias = original_bias - self.epsilon
            y_pred_minus = np.dot(X, self.weights) + self.bias
            loss_minus = self.loss_fn(y, y_pred_minus)

            db = (loss_plus - loss_minus) / (2 * self.epsilon)

            self.bias = original_bias  # restore original bias

            # Gradient descent update
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict(self, X):
        X = np.array(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return np.dot(X, self.weights) + self.bias

# ----- Example loss function: MSE -----
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)


In [ ]:

X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegressionGD(
    learning_rate=0.01,
    n_iterations=10,
    loss_fn=mse_loss
)
model.fit(X, y)

preds = model.predict([6, 7])
print("Predictions:", preds)


In [ ]:
X = np.array([10, 2, 30, 14, 13, 7]) #age 
y = np.array([0, 0, 1, 1, 1, 0]) #anyone above 13 is called 1, else 0

model = LinearRegressionGD(
    learning_rate=0.001,
    n_iterations=300,
    loss_fn=mse_loss
)
model.fit(X, y)

preds = model.predict([16, 7, 13])
print("Predictions:", preds)


In [ ]:
preds = model.predict([16, 7, 13, 12, 18, 19])
preds

In [ ]:
X = np.array([10, 2, 30, 14, 13, 7])
X = X.reshape(-1, 1)

In [ ]:
w = np.random.randn(1)

In [ ]:
w

In [ ]:
np.dot(X, w)

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
sigmoid(-5)

np.float64(0.0066928509242848554)

In [ ]:
sigmoid(-15), sigmoid(15)

In [ ]:
[1, 0.9, 0.1, .05] <> [1, 1, 0, 0]

yactual * log(yp)

In [5]:
def sg_mse_loss(y_true, y_pred):
    y_pred = sigmoid(y_pred)
    return np.sum( -(y_true * y_pred + (1-y_true)*(1-y_pred)))
#   return np.sum( (y_true * np.log(y_pred) + (1-y_true)*np.log(1-y_pred)))


X = np.array([10, 2, 30, 14, 13, 7, 12, 11.5, 13.1, 13.2, 12.9]) #age 
y = np.array([0,  0, 1,  1,  1,  0, 0,  0,    1,    1, 0]) #anyone above 13 is called 1, else 0

model = LinearRegressionGD(
    learning_rate=0.01,
    n_iterations=3000,
    loss_fn=sg_mse_loss
)
model.fit(X, y)

preds = model.predict([16, 7, 13])
print("Predictions:", preds)


[[10. ]
 [ 2. ]
 [30. ]
 [14. ]
 [13. ]
 [ 7. ]
 [12. ]
 [11.5]
 [13.1]
 [13.2]
 [12.9]]
(11, 1)
Weights, Bias:  [-0.95667795] -0.8498487099178524
Loss:  -5.940089104334993
Weights, Bias:  [-0.95783522] -0.8504125975291237
Loss:  -5.940254601484814
Weights, Bias:  [-0.95898929] -0.8509750204329285
Loss:  -5.9404191970677624
Weights, Bias:  [-0.96014018] -0.8515359861343745
Loss:  -5.9405828985539415
Weights, Bias:  [-0.96128792] -0.8520955020781733
Loss:  -5.940745713328517
Weights, Bias:  [-0.96243251] -0.852653575652637
Loss:  -5.940907648692525
Weights, Bias:  [-0.96357399] -0.853210214187458
Loss:  -5.941068711864825
Weights, Bias:  [-0.96471235] -0.8537654249554854
Loss:  -5.941228909982742
Weights, Bias:  [-0.96584763] -0.8543192151740568
Loss:  -5.941388250103511
Weights, Bias:  [-0.96697983] -0.8548715920036669
Loss:  -5.941546739205381
Weights, Bias:  [-0.96810898] -0.8554225625510752
Loss:  -5.941704384188721
Weights, Bias:  [-0.9692351] -0.855972133866642
Loss:  -5.941861191

In [ ]:
x_test = [16, 7, 13, 12, 14, 15, 16, 11, 11.5, 13.2]
preds = model.predict(x_test)

In [ ]:
preds

In [ ]:
result = sigmoid(preds)

In [ ]:
list(zip(x_test, result))

In [ ]:
def sg_mse_loss(y_true, y_pred):
    y_pred = sigmoid(y_pred)
    return np.mean( -(y_true * np.log(y_pred) + (1-y_true)*np.log(1-y_pred)))
#   return np.sum( (y_true * np.log(y_pred) + (1-y_true)*np.log(1-y_pred)))


X = np.array([10, 2, 30, 14, 13, 7, 12, 11.5, 13.1, 13.2, 12.9]) #age 
# y = np.array([0,  0, 1,  1,  1,  0, 0,  0,    1,    1, 0]) #anyone above 13 is called 1, else 0
y = np.array([1 if x>=13 else 0 for x in X])
model = LinearRegressionGD(
    learning_rate=0.001,
    n_iterations=3000,
    loss_fn=sg_mse_loss
)
model.fit(X, y)

preds = model.predict([16, 7, 13])
print("Predictions:", preds)


[[10. ]
 [ 2. ]
 [30. ]
 [14. ]
 [13. ]
 [ 7. ]
 [12. ]
 [11.5]
 [13.1]
 [13.2]
 [12.9]]
(11, 1)
Weights, Bias:  [1.19379789] -0.619458323306207
Loss:  5.688878712896192
Weights, Bias:  [1.18878833] -0.6199904847492523
Loss:  5.663500428590105
Weights, Bias:  [1.18377901] -0.6205225233031766
Loss:  5.638124793265054
Weights, Bias:  [1.17876995] -0.6210544400463616
Loss:  5.612751834078568
Weights, Bias:  [1.17376114] -0.6215862360156224
Loss:  5.587381553909794
Weights, Bias:  [1.16875259] -0.6221179054882922
Loss:  5.562013992522144
Weights, Bias:  [1.16374431] -0.6226494511496896
Loss:  5.536649178929848
Weights, Bias:  [1.15873628] -0.623180870613679
Loss:  5.5112871288920395
Weights, Bias:  [1.15372852] -0.6237121612743004
Loss:  5.485927865348572
Weights, Bias:  [1.14872102] -0.6242433243159398
Loss:  5.460571411818581
Weights, Bias:  [1.14371379] -0.6247743568090738
Loss:  5.4352177958866275
Weights, Bias:  [1.13870683] -0.6253052606332212
Loss:  5.409867033606343
Weights, Bias: 

In [7]:
x_test = [16, 7, 13, 12, 14, 15, 16, 11, 11.5, 13.2]
preds = model.predict(x_test)
result = sigmoid(preds)
list(zip(x_test, result))

[(16, np.float64(0.6186048735238665)),
 (7, np.float64(0.41671862232532997)),
 (13, np.float64(0.5523905904385008)),
 (12, np.float64(0.5297736281099595)),
 (14, np.float64(0.5747928371373152)),
 (15, np.float64(0.5968920807382361)),
 (16, np.float64(0.6186048735238665)),
 (11, np.float64(0.5070337274611377)),
 (11.5, np.float64(0.5184132122381288)),
 (13.2, np.float64(0.5568911014493176))]

In [8]:
result > 0.55

array([ True, False,  True, False,  True,  True,  True, False, False,
        True])

*Question:*
    
    def confusion_matrix(y_true, y_pred):
        # Print confusion matrix

    def precision(), recall, f1_score

In [23]:
def confusion_matrix(y_true, y_pred):
    n_total = len(y_true);
    true_positive= true_negative= false_positive = false_negative = 0
    for i in range (n_total):
        if (y_true[i]):
            if (y_pred[i]):
                true_positive+=1
            else:
                false_negative+=1
        else:
            if (y_pred[i]):
                false_positive+=1
            else:
                true_negative+=1
    return ( true_positive,false_positive,true_negative, false_negative)
    


In [24]:
# y_act = np.array([True, False, True,  True, False, False,  True, False,  True,
#         True])
# y_pred= np.array([True, False, True, False,  True,  True,  True, False, True,
#         True])
y_act = np.array([1, 0, 1,  1, 0, 0,  1, 0,  1,
        1])
y_pred= np.array([1, 0, 1, 0,  1,  1,  1, 0, 1,
        1])


tp,fp,tn, fn= confusion_matrix(y_act,y_pred)
ap = tp + fn
an = tn + fp
print (f"Actual Positive:{ap}   True Positive:{tp}   False Positive:{fp}")
print (f"Actual Negative:{an}   True Negative:{tn}   False Negative:{fn}")

precision = tp/(tp + fp)
recall = tp/ap
f1_score = (2 * precision * recall)/(precision+recall)

Actual Positive:6   True Positive:5   False Positive:2
Actual Negative:4   True Negative:2   False Negative:1


In [ ]:

x_test = [16, 7, 13, 12, 14, 15, 16, 11, 11.5, 13.2]
preds = model.predict(x_test)
result = sigmoid(preds)
list(zip(x_test, result))


[1 0 1 0 1 1 1 0 0 1]
[1 0 1 0 1 1 1 0 0 1]


In [39]:
y_act = np.array([1 if x>=13 else 0 for x in x_test])
threshold = 0.6
y_pred = np.array([1 if r>=threshold else 0 for r in result])

print ("Actual   :", y_act)
print ("Predicted:", y_pred)

tp,fp,tn, fn= confusion_matrix(y_act,y_pred)
ap = tp + fn
an = tn + fp

precision = tp/(tp + fp)
recall = tp/ap
f1_score = (2 * precision * recall)/(precision+recall)
print (f"At Threshold: {threshold} - Precision: {precision}, Recall: {recall}, F1Score: {f1_score}")

Actual   : [1 0 1 0 1 1 1 0 0 1]
Predicted: [1 0 0 0 0 0 1 0 0 0]
At Threshold: 0.6 - Precision: 1.0, Recall: 0.3333333333333333, F1Score: 0.5
