In [113]:
import numpy as np

def differential(fn, input, delta):
    output1 = fn(input)
    output2 = fn(input+delta)
    d = (output2 - output1) / delta
    return d

def rmse_loss(y_actual, y_pred):
    error = np.sqrt(np.mean((y_pred - y_actual) ** 2))
    return error

# def mse_loss(y_true, y_pred):
#     return np.mean((y_true - y_pred) ** 2)
def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

In [122]:
import numpy as np
class LinearRegressionGD:
    def __init__(self,learning_rate, n_iterations,loss_fn,
                 epsilon= 1e-5):
        self.learning_rate=learning_rate
        self.n_iterations= n_iterations
        self.epsilon = epsilon
        self.loss_fn = loss_fn

    def fit(self, X, y):
        X= np.array(X)
        y= np.array(y)
        if (X.ndim == 1):
            X = X.reshape(-1,1)
        
        n_samples, n_features = X.shape
        self.weights = np.random.randn(n_features,1)
        self.bias= np.random.randn()
        dw = np.zeros_like (self.weights)
        
        weights_plus = self.weights.copy()
        for n in range(self.n_iterations):
            y_pred=(X@self.weights)+self.bias
            loss = self.loss_fn(y,y_pred)
            print("Weights, Bias: ", self.weights, self.bias)
            print("Loss: ", loss)
            for i in range(len(self.weights)):
                weights_plus[i] = self.weights[i] + self.epsilon
                y_pred_plus = (X@weights_plus)+self.bias
                loss_plus = self.loss_fn(y,y_pred_plus)
                dw[i] = loss_plus/self.epsilon
            bias_plus = self.bias + self.epsilon
            y_pred_plus = (X@self.weights)+bias_plus
            loss_plus = self.loss_fn(y,y_pred_plus)
            db = loss_plus/self.epsilon
            self.weights -=self.learning_rate * dw
            self.bias -=self.learning_rate * db

    def predict(self, X):
        X=np.array(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return (X@self.weights) + self.bias




In [ ]:
import numpy as np

class LinearRegressionGD2:
    def __init__(self, learning_rate=0.01, n_iterations=1000, loss_fn=None, epsilon=1e-5):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.loss_fn = loss_fn
        self.epsilon = epsilon  # small perturbation for numerical gradient
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
            print(X)
            print(X.shape)
        
        n_samples, n_features = X.shape

        # Randomly initialize weights and bias
        self.weights = np.random.randn(n_features)
        self.bias = np.random.randn()

        for _ in range(self.n_iterations):
            y_pred = np.dot(X, self.weights) + self.bias
            loss = self.loss_fn(y, y_pred)
            print("Weights, Bias: ", self.weights, self.bias)
            print("Loss: ", loss)
            
            # Approximate gradient for weights
            dw = np.zeros_like(self.weights)
            for i in range(len(self.weights)):
                original_value = self.weights[i]

                self.weights[i] = original_value + self.epsilon
                y_pred_plus = np.dot(X, self.weights) + self.bias
                loss_plus = self.loss_fn(y, y_pred_plus)
                

                self.weights[i] = original_value - self.epsilon
                y_pred_minus = np.dot(X, self.weights) + self.bias
                loss_minus = self.loss_fn(y, y_pred_minus)

                dw[i] = (loss_plus - loss_minus) / (2 * self.epsilon)

                self.weights[i] = original_value  # restore original weight

            # Approximate gradient for bias
            original_bias = self.bias

            self.bias = original_bias + self.epsilon
            y_pred_plus = np.dot(X, self.weights) + self.bias
            loss_plus = self.loss_fn(y, y_pred_plus)

            self.bias = original_bias - self.epsilon
            y_pred_minus = np.dot(X, self.weights) + self.bias
            loss_minus = self.loss_fn(y, y_pred_minus)

            db = (loss_plus - loss_minus) / (2 * self.epsilon)

            self.bias = original_bias  # restore original bias

            # Gradient descent update
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate * db

    def predict(self, X):
        X = np.array(X)
        if X.ndim == 1:
            X = X.reshape(-1, 1)
        return np.dot(X, self.weights) + self.bias

In [123]:
import numpy as np
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegressionGD(learning_rate=0.01, n_iterations=10, 
                           loss_fn=mse_loss)
model.fit(X,y)
y_pred= model.predict(X)


Weights, Bias:  [[-0.14436676]] -0.4001383519857285
Loss:  54.734833850299744
Weights, Bias:  [[-54734.56244917]] -54735.0973239789
Loss:  53928563395.85464
Weights, Bias:  [[-5.39285634e+13]] -53928563446210.83
Loss:  5.234921918016733e+28
Weights, Bias:  [[-5.23492192e+31]] -5.234921918016733e+31
Loss:  4.932793347791758e+64
Weights, Bias:  [[-4.93279335e+67]] -4.932793347791758e+67
Loss:  4.379841038163351e+136
Weights, Bias:  [[-4.37984104e+139]] -4.3798410381633506e+139
Loss:  3.4529413535243673e+280
Weights, Bias:  [[-3.45294135e+283]] -3.452941353524367e+283
Loss:  inf
Weights, Bias:  [[-inf]] -inf
Loss:  inf
Weights, Bias:  [[-inf]] -inf
Loss:  inf
Weights, Bias:  [[-inf]] -inf
Loss:  inf


/tmp/ipykernel_1065005/834518298.py:16: RuntimeWarning: overflow encountered in square
  return np.mean((y_true - y_pred) ** 2)


In [46]:
x = [[1,2,3],[4,5,6],[7,8,9], [10,11,12]]
X = np.array(x)
w= np.random.randn(3)

print(X)
print(w)
print("---------")
y1= X@w 
y2 = X@w + 3
print(y1)
print(y2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[-0.48933722 -0.80459114 -0.21269764]
---------
[ -2.73661242  -7.25649041 -11.7763684  -16.2962464 ]
[  0.26338758  -4.25649041  -8.7763684  -13.2962464 ]


In [99]:
import numpy as np
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
X= np.array(X)
# print(X.ndim)
# if X.ndim == 1:
#     X.reshape(-1,1)
#     print(X)
#     print(X.shape)


if X.ndim == 1:
        X = X.reshape(-1, 1)
        # print(X)
        # print(X.shape)
    
n_samples, n_features = X.shape

weights = np.random.randn(n_features,1)
bias= np.random.randn()
dw = np.zeros_like (weights)
weights_plus = weights.copy()
# print(weights)
# print(weights_plus)
weights_plus[0] +=1
print(dw)
print(weights)
# model = LinearRegressionGD(learning_rate=0.01, number_iterations=100, 
#                            loss_fn=MSE_lossfunction)
# model.fit(X,y)
# y_pred= model.predict(X)


[[0.]]
[[1.98508459]]


In [ ]:
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegressionGD(learning_rate=0.01, number_iterations=100, 
                           loss_fn=MSE_lossfunction)
model.fit(X,y)
y_pred= model.predict(X)

In [91]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.copy()  # Creates an independent copy

array2[0] = 100  # Modify array2
print("array1:", array1)  # Original remains unchanged
print("array2:", array2)  # Modified copy


array1: [1 2 3 4]
array2: [100   2   3   4]
